### ISSUE TITLE
Incompatibility with Windows

### ISSUE THREAD

**Issue by Suphax** [alexander-heimbuch/watch-together#3]
Unsure if this is still maintained but either attempting to start, or run dev fails on Windows in the cleanup script. Git bash states the syntax is incorrect, as well as Powershell.
When run individually, the commands execute without issue.
Specifically running the cleanup script as this causes `npm start` and `npm run dev` to fail anyway.

No issues during `npm install`, with the exclusion of fsevents being omitted due to it being Windows. I attempted `npm i -f` *just incase* it would alter anything; it made no difference.

Even if Windows is not a target for this script currently, a change in the readme noting the incompatibility would be useful.

```bash
$ npm run cleanup

> watch-together@1.0.0 cleanup C:\Users\Jack\Documents\watch-together
> rm -rf dist/ && mkdir -p dist/

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! watch-together@1.0.0 cleanup: `rm -rf dist/ && mkdir -p dist/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the watch-together@1.0.0 cleanup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jack\AppData\Roaming\npm-cache\_logs\2020-09-01T00_31_11_492Z-debug.log

Jack@Jacks-PC MINGW64 ~/Documents/watch-together (master)
$  rm -rf dist/

Jack@Jacks-PC MINGW64 ~/Documents/watch-together (master)
$ mkdir -p dist/

Jack@Jacks-PC MINGW64 ~/Documents/watch-together (master)
$ rm -rf dist/ && mkdir -p dist/

Jack@Jacks-PC MINGW64 ~/Documents/watch-together (master)
$
```

**Comment by alexander-heimbuch** [comment]
Yes it is still maintained, I also need to add a https proxy to get rid of the manual cert process. Feel free to replace the unix `rm` and `mkdir` with a node based equivalent.

**Comment by alexander-heimbuch** [comment]
@Suphax I've updated some build tools, please have a look if this now also runs on Windows. Feel free to reopen this ticket if that's not the case.
